### ISSUE TITLE
Bruce Rodrigues Onboarding 

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [clevercanary/data-browser#1]
- [x] Review [Clever Canary Team Handbook](https://docs.google.com/document/d/1ETck6lmEgCe6h3VBLuJ281PExn7C9bA8vZgKq5-PRo0)
- [x] Onboarding (Slack, GitHub, GitHub Projects, Harvest)
- [x] Initial kickoff meeting

**Comment by NoopDog** [comment]
Done
