### ISSUE TITLE
Add configurable favicons for each site

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [clevercanary/data-browser#167]
#### Approach
* Take a look at the current best practices for including favicons (e.g. what are the recommended set of sizes we need to support in 2022!).
* Generate favicons in the required sizes for AnVIL, LungMAP and HCA.

#### Approach
* Configure favicons for AnVIL, LungMAP and HCA.

#### Definition of Done
* Favicon correctly configured for each site.

**Comment by MillenniumFalconMechanic** [comment]
Thank you Kaspars!

**Comment by MillenniumFalconMechanic** [comment]
Hi @BruceRodrigues, Kaspars has created a set of favicons for each site (see "Step 1" in description above). Can you take a look at "Step 2" and integrate the favicons into the site configs for each site?

**Comment by NoopDog** [comment]
@BruceRodrigues, what is the plan for this one? One idea is that we copy the favicon to the appropriate directory on build or dev each time we run it just like we do for the configs.
