### ISSUE TITLE
Explore using basepath to host the prod build under /explore  instead of pages directory folder structure

### ISSUE THREAD

**Issue by NoopDog** [clevercanary/data-browser#189]
https://nextjs.org/docs/api-reference/next.config.js/basepath

```
module.exports = {
  basePath: '/explore',
}
```

On the prod s3 bucket I need a structure like:

/explore
---- index.html
----_next/

Currently, references to static assets inside index.html look like this:
script src="/_next/static/chunks/framework-5f4595e5518b5600.js"

I think we need them to be more like:
script src="/`explore/`_next/static/chunks/framework-5f4595e5518b5600.js"

Then, we can remove adding the /explore  directory in the pages directory

<img width="251" alt="image" src="https://user-images.githubusercontent.com/3239697/177923700-0913f8d7-9ff7-47d2-bbca-dd343d18f6de.png">

Lets discuss!

**Comment by BruceRodrigues** [comment]
This ticket was merged in https://github.com/clevercanary/data-browser/pull/203
