### ISSUE TITLE
Selected tab not updated on click of "Datasets" link in header

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [clevercanary/data-browser#252]
#### What I Did
1. Navigate to the [files tab](https://anvil.dev.singlecell.gi.ucsc.edu/explore/files).
2. Click "Datasets" in the header.

#### What I Expected
1. Datasets entity list is displayed.
2. Datasets tab highlighted as selected tab.

#### What Happened Instead
1. Datasets entity list is displayed.
2. Files tab remains highlighted as selected tab.

**Comment by BruceRodrigues** [comment]
Hey @MillenniumFalconMechanic !
I couldn't reproduce this, maybe I misunderstood the bug?
I tested on chrome, safari, and firefox.

![tabs](https://user-images.githubusercontent.com/4441364/179879149-9d8cb3bb-c4e0-4429-9c34-4f59cda071f9.gif)

**Comment by MillenniumFalconMechanic** [comment]
Hi @BruceRodrigues, thanks for you taking a look. The video below shows my steps to reproduce. It's hard to see but I am clicking on the "Datasets" link in the header. The datasets entity list loads correctly but the files tab remains highlighted as the selected tab.

https://user-images.githubusercontent.com/2446424/183509316-8677a0dc-eb48-4844-8952-6e02ceea54f8.mp4
