### ISSUE TITLE
[AnVIL DX] Refine summary implementation mobile UI

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [clevercanary/data-browser#265]
It looks like longer summary labels are not quite fitting within the specified bounds of the summary counts.

**Comment by frano-m** [comment]
Review [mock](https://www.figma.com/file/i4uZsYkKAML9ivi2TIo6ug/explore-dashboard?node-id=1148%3A19984).
`Participants` label is outside of padding:
![Image](https://user-images.githubusercontent.com/18710366/180123186-b867970c-37e7-4bb1-8f5f-72308ce653c7.png)


Implementation of mock (galaxy fold at 280px):
![Image](https://user-images.githubusercontent.com/18710366/180124356-9627d979-7254-42b7-8ae1-cbe3d8598b43.png)


Implementation of mock (iPhone SE at 375px):
![Image](https://user-images.githubusercontent.com/18710366/180124272-0cb65802-761c-4603-b045-e35e54c3cf77.png)

**Comment by KasparsNaglis** [comment]
1. Regarding "Participants label is outside of padding:" just set each "count" min-width to 25%, and if some of the labels need more width (like participants), let them get it. 
2. Implementation of mock (galaxy fold at 280px): Ignore everything under 360px. 
3. Implementation of mock (iPhone SE at 375px): Something isn't right with the content left/right margin. It should be 16px. And shorten "Estimated" to "Est.".

**Comment by NoopDog** [comment]
Thanks, Kaspars. @frano-m does this give you the information you need for this area?

**Comment by MillenniumFalconMechanic** [comment]
We could possibly configure a "short label" to handle transforms from "estimated" to "est". Another possibility is to configure a smaller set of summary values (e.g. drop "files" on mobile).

**Comment by MillenniumFalconMechanic** [comment]
Obsolete.
