### ISSUE TITLE
Update ESLint settings to sort imports

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [clevercanary/data-browser#271]
We tend to group imports into two sections: core dependencies and app dependencies ([see example](https://github.com/clevercanary/data-browser/blob/main/explorer/app/components/Index/components/Hero/hero.stories.tsx#L1-L11)); is it possible to maintain these groupings and sort within each group? No worries if not, the fallback is to sort as a single group of imports.

**Comment by NoopDog** [comment]
Implemented!
