### ISSUE TITLE
Clarify cross-site typography

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [clevercanary/data-browser#277]
We have a few questions about the UI design and customization options for fonts across sites.

I think we would be happy with one custom font for each site for certain headings to maintain a "brand" like:

HCA - H1 - DIN
AnVIL - H1 - Open Sans

Then, everything else is Inter.

In the mocks, we have two font specifications [here](https://www.figma.com/file/i4uZsYkKAML9ivi2TIo6ug/explore-dashboard?node-id=470%3A4666) and [here](https://www.figma.com/file/i4uZsYkKAML9ivi2TIo6ug/explore-dashboard?node-id=587%3A5658)

We are not sure how these are to be used.

Our questions are:

* Can these fonts be unified so that everything is the same across sites except the font specification for the headings?
* Or, do you need to adjust the heading heights, etc. based on the heading font's characteristics?
* How can we streamline this to make it "configurable" so that as much as possible is the same across sites while allowing different heading fonts per site for branding?
* What changes must be made to the mocks if we streamline the typography settings?

Thanks!
D

**Comment by KasparsNaglis** [comment]
Consider [these](https://www.figma.com/file/i4uZsYkKAML9ivi2TIo6ug/explore-dashboard?node-id=470%3A4666) as Global CSS Classes/Variables. 

By default, the system uses [AnVIL (Inter) Typography classes. ](https://www.figma.com/file/i4uZsYkKAML9ivi2TIo6ug/explore-dashboard?node-id=470%3A4666) 

For HCA, we override/edit the values (Typeface, size, line height) of [these classes ](https://www.figma.com/file/i4uZsYkKAML9ivi2TIo6ug/explore-dashboard?node-id=587%3A5658) Everything else we leave as is. 

I don't find it practical to specify HTML Headings and paragraph styles strickly. 
By default we can set that H1 uses 





We don't specify that H1 is always 30px. Instead, we can add any of the given classes like "text-heading-large" or even "text-body-400". This gives us the flexibility to use whatever HTML tad we need in combination with the desired style.

**Comment by MillenniumFalconMechanic** [comment]
Thank you Kaspars!
