### ISSUE TITLE
Refine typography

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [clevercanary/data-browser#287]
See [clarification](https://github.com/clevercanary/data-browser/issues/277).

#### Font Family
* Default is Inter.
* HCA/LungMAP requires overrides with DIN.
~~* AnVIL requires overrides with Open Sans.~~
* Update Figma to include DIN fonts.

#### Color
* Fallback for all is `ink`.

**Comment by NoopDog** [comment]
Update, we will use Inter as the default for AnVIL
