### ISSUE TITLE
Add typography specification for Open Sans for AnVIL

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [clevercanary/data-browser#288]
#### Need
We would like to update the AnVIL heading-related typography to be Open Sans (rather than the default Inter). Similar to the [HCA typography specification](https://www.figma.com/file/i4uZsYkKAML9ivi2TIo6ug/explore-dashboard?node-id=587%3A5658), we need a heading-related typography spec.

**Comment by KasparsNaglis** [comment]
I would not recommend it. 
Opens Sans and Inter are almost indistinguishable. An untrained eye can't tell them apart. Just adds unnecessary complexity. 

But let me know if you will want to continue.

**Comment by NoopDog** [comment]
Awesome Thanks. D
