### ISSUE TITLE
Create analysis portal icons

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [clevercanary/data-browser#304]
### Need
We need icons for LGEA, Shiny and ToppCell analysis portals.

#### LGEA
![logo-lgea](https://user-images.githubusercontent.com/2446424/180510302-a044d419-d584-4d22-990b-d0d5874f4ade.png)

#### Shiny
![logo-shiny](https://user-images.githubusercontent.com/2446424/180510292-12ae9f88-1a25-4d19-9ce0-6e0e1fff5a8c.png)

#### ToppCell
To get this to a square logo:
1. Remove the row min/row max bar.
2. Remove the individual squares and keys  (e.g. A, A1, A2) section at the top of the image.
3. Remove the horizontal rainbow bar under the horizontal "Ukrainian flag" bar and replace it with the horizontal Ukrainian flag.
4. Remove the vertical "Ukrainian flag" to the right of the image.
 
![logo-toppcell](https://user-images.githubusercontent.com/2446424/180510308-63146e6e-2b47-404d-b3bd-b10fa4d72ca9.svg)

### Source
[See original ticket](https://github.com/DataBiosphere/data-browser/issues/2732).

**Comment by KasparsNaglis** [comment]
https://www.figma.com/file/i4uZsYkKAML9ivi2TIo6ug/explore-dashboard?node-id=237%3A1534

**Comment by NoopDog** [comment]
Done Thanks! D
