### ISSUE TITLE
NCPI + Dug Topnav Logo

### ISSUE THREAD

**Issue by NoopDog** [clevercanary/data-browser#326]
#### Need
We are demoing a mix of the Dug semantic search technology and the NCPI dataset catalog. We have created click-through mocks for this effort and now need a logo to easily differentiate the NCPI site from the NCPI + Dug site.

#### Approach
1. On simple idea is just to use the NCPI cloud logo we have and add a "+ Dug" text to the right to create a new, longer logo.  like "(NCPI) + Dug where ( NCPI) is the NCPI cloud logo.}

If you want to get fancy... (no need but just giving context)
2.  Dug is named after the dog in the Disney movie "Dug" e.g. "My name is Dug. I have just met you, and I love you!"  https://pixar.fandom.com/wiki/Dug?file=Russell_dug_carl_fredricksen_in_pixars_up-wide.jpg
3. This is a throwaway logo that can be fun but should not violate copyright. 

Dug "Points the way."
https://pixar.fandom.com/wiki/Dug?file=Screen_Shot_2011-12-07_at_8.09.35_AM.png

4. Please timebox this for an hour or so.

**Comment by KasparsNaglis** [comment]
https://www.figma.com/file/i4uZsYkKAML9ivi2TIo6ug/explore-dashboard?node-id=1378%3A23933

I think this for "throwaway logo" will do just fine. "Dug" is written in a playful typeface, which resonates with the cartoon character very well without incorporating an actual dog.

**Comment by NoopDog** [comment]
Complete. Thanks!
