### ISSUE TITLE
Evaluate v3 (beta version) of next-optimized-images

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [clevercanary/data-browser#40]

**Comment by BruceRodrigues** [comment]
I did a little research and decided to not go ahead with the `next-optimized-images` v3 for the given reasons:
- The problem with storybook was easily solved by changing the image src from commonJs format to use ES modules. Which end up being a better API for the `<StaticImage>` component as well.
- [The thread for version 3](https://github.com/cyrilwanner/next-optimized-images/issues/120) of `next-optimized-images` was created in Nov 2019, so it has been in development for more than 2 years, and mostly all recent posts on the thread are asking about updates. It seems that the maintainer doesn't have a lot of time to keep updating this, so moving to a beta version seems risk in the long run.
