### ISSUE TITLE
Update hca-dcp file entity list config

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [clevercanary/data-browser#401]
#### Need
The `hca-dcp` entity list configurations are currently in a deprecated format and needs to be incrementally updated to match the current preferred paradigm. We will approach the refactor incrementally, starting with the files entity.

#### Approach
* Follow the approach/spec described in the [configuration guide](https://github.com/clevercanary/data-browser/blob/main/docs/configuration-guide.md) for configuring entity lists.
* Use the `ncpi-catalog` `studiesEntityConfig.ts` and its corresponding view builder and transformer as an example.
* Replace any reference to the `Text` component to use the `Cell` component instead. For example,

```
export const filesToFileNameColumn = (
  file: FilesResponse
): React.ComponentProps<typeof C.Text> => {
  if (!file.files?.[0]) {
    return {};
  }

  return {
    children: file.files[0].name,
    customColor: "ink",
    variant: "text-body-400",
  };
};
```

should be replaced with

```
export const buildFileName = (
  file: FilesResponse
): React.ComponentProps<typeof C.Cell> => {
  return {
    value: getFileName(response),
  };
};
```
* Any sanitizing of an entity value should occur in the transformer and not the view model builder. In the example above, the following check should be moved from the view model builder to the transformer:

```
if (!file.files?.[0]) {
  return {}; // Note: when moving this to the transformer, this should return "" not {} (as the transformer function should be returning a string)
}
```

#### Notes
* The existing `FilesResponse` response model can be reused as-is but needs to be moved to the appropriate location.
* The existing `filesTransfomer.ts` is currently a mix of a view model builder and transformer functionality. Split/move/update the functionality as needed then remove this file.
* There is a slight modification to the location of the`hca-dcp` view builders and transformers: they both need to fall under an `azul` directory. So for example, `viewModelBuilders/azul/hca-dcp/` and `apis/azul/hca-dcp/`.

#### Definition of Done
* Files entity config is updated to match spec.
* `hca-dcp`-specific view builders file created.
* `hca-dcp`-specific transformers file created (with the existing `fileTransfomer.ts` removed).

**Comment by jpaten** [comment]
Just to check: Is it just the view builders and transformers that need to go in an Azul folder or does the entities.ts need to as well?

**Comment by MillenniumFalconMechanic** [comment]
`entities.ts` (containing the `FilesResponse`) should go into an Azul folder under `apis`.
