### ISSUE TITLE
DIN Font on HCA explorer does not match current HCA

### ISSUE THREAD

**Issue by NoopDog** [clevercanary/data-browser#442]
#### Need
We want to keep as close as we can to the HCA branding. Currently, on [the](https://hca.dev.singlecell.gi.ucsc.edu/explore/files) the font is heaver for H1 at least than the  current HCA DCP Site.

Dev Site see the (Explore Data: DCP 2.0 Data View) text.
<img width="823" alt="image" src="https://user-images.githubusercontent.com/3239697/183978491-dd01bac2-6fab-4590-8598-e0b4f9b7b13c.png">

Prod site
<img width="716" alt="image" src="https://user-images.githubusercontent.com/3239697/183978588-f63df4a1-7b85-486c-ba1e-133f7c55d1de.png">

#### Approach
Please review the font specifications and mocks for HCA where DIN is used (ignoring inter) and determine which ones do not match the current live site.  Then let's review which ones we think should match the live site and either update the implementation and font style specification in Figma if required. 

#### DOD
1. We have a clear specification of which DIN font usages will match or differ from HCA prod.
2. The Figma and site are updated to use the updated specification.

**Comment by frano-m** [comment]
https://docs.google.com/spreadsheets/d/1yIBJed21OaDTmDeuB9SDYnF5ECfTkRTpwlkC_vRdrnI/edit#gid=0

**Comment by NoopDog** [comment]
@frano-m The figma specification is now updated for this one and It can be worked on.

**Comment by NoopDog** [comment]
@frano-m can you update this with the latest findings? Thanks!
