### ISSUE TITLE
Kaspars Naglis Onboarding

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [clevercanary/data-browser#5]
- [ ] Review [Clever Canary Team Handbook](https://docs.google.com/document/d/1ETck6lmEgCe6h3VBLuJ281PExn7C9bA8vZgKq5-PRo0)
- [ ] Onboarding (Figma, Slack, GitHub, GitHub Projects, Harvest)
- [ ] Initial kickoff meeting

**Comment by KasparsNaglis** [comment]
All done. 
Had a few issues with Harvest, apparently, it doesn't work with the Brave browser (Chrome-based).
Not sure if I have to but I can't tick off the task checkboxes.

**Comment by MillenniumFalconMechanic** [comment]
Thanks Kaspars!

**Comment by NoopDog** [comment]
Complete
