### ISSUE TITLE
Implement "Sign in with Google" using "Google Identity Services for Web" 

### ISSUE THREAD

**Issue by NoopDog** [clevercanary/data-browser#528]
#### Need
To access controlled access data, we need to know who users are so that we can determine what data to display to them. The back-end systems use the Google Cloud, so we need to use a system compatible with Google to generate access tokens. 

#### Approach
The older "Google Sign-In JavaSript Platform Library is being discontinued on March 31, 2023. For this project, we need to use the new "Sign in with Google" using the new Google Identity SDK.  https://developers.google.com/identity

**Comment by MillenniumFalconMechanic** [comment]
Completed.
