### ISSUE TITLE
Make details.tsx take a configurable  title

### ISSUE THREAD

**Issue by NoopDog** [clevercanary/data-browser#561]
#### Need
Currently, the details section has a fixed title, "Project Details" this is not suitable for all entity types.
see
`  <CollapsableSection collapsable title="Project Details">`

#### Approach
TBD @frano-m can you determine the best way to make this configurable?

**Comment by frano-m** [comment]
### Approach
- Add an additional prop `title` to the `Details` component.
- Find all uses of `C.Details` in the `viewModelBuilders` and `projectViewModelBuilder` files e.g. `explorer/app/viewModelBuilders/azul/anvil/common/viewModelBuilders.ts` and add the `title` prop with corresponding text to the model.
