### ISSUE TITLE
Set up CC Data Browser

### ISSUE THREAD

**Issue by frano-m** [clevercanary/data-browser#570]
Set up [CC Data Browser](https://github.com/clevercanary/data-browser).

When making a PR make sure you select `clevercarary/data-browser` as the base repo:

![Image](https://user-images.githubusercontent.com/18710366/191863286-09fbc514-bc3a-4bc3-8c9d-1b8b803d7c45.png)

Once selected, the comparing changes should look like this:

![Image](https://user-images.githubusercontent.com/18710366/191863396-a83f776b-9dd6-4a3b-a8e9-b0daf1312e14.png)

The forked code we are working on is `/explorer`.

To run:

- Change directory to `explorer`.
- Use any of the scripts in the `package.json` e.g. `npm run dev:hca-dcp` for HCA, or `npm run dev:anvil` for AnVIL and so on.
- For Storybook, run `npm run storybook`.

**Comment by NoopDog** [comment]
Hey @Arctenik, can this be closed, or do you have any questions?

**Comment by Arctenik** [comment]
Should be good to close!
