### ISSUE TITLE
Allow study description component to accept HTML

### ISSUE THREAD

**Issue by NoopDog** [clevercanary/data-browser#610]
#### Need

The dbGaP response has a few types of HTML markdown elements that provide for the basic formatting of the description. Currently, the description section on AnVIL catalog displays the markdown instead of using it to format the description.

#### Approach
TBD - Update [descritption.tsx ](https://github.com/clevercanary/data-browser/blob/1e80477e5e975a06b5784f162263d6de602ce538/explorer/app/components/Project/components/Description/description.tsx)to take HTML?

Let's discuss options.

### DOD
- The HTML items such as P and Links show properly in the detail pages.

**Comment by frano-m** [comment]
@NoopDog TODO reminder - investigate potential uses for MDX.
