### ISSUE TITLE
[AnVIL DX] Refactor category key and label

### ISSUE THREAD

**Issue by frano-m** [clevercanary/data-browser#665]
### Need

The entity and category config rely on category keys and labels. Update and/or create a new `category.ts` file for each site where each category key and label are defined.

See `explorer/site-config/anvil-catalog/category.ts` as an example.

Use the defined category key and label for the site configuration `categoryConfigs` and also the entity configuration `column` configuration i.e. `header` and `id` fields.

Each site may have inconsistencies or incomplete keys/labels, some may be pluralised whereas others are not. These should be resolved as much as possible for consistency.

### Approach

Make a note of the inconsistent key/labels for discussion and resolution.

**Comment by MillenniumFalconMechanic** [comment]
Obsolete.
