### ISSUE TITLE
Configurable Site Header UI

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [clevercanary/data-browser#7]
[Design doc](https://docs.google.com/document/d/1Z7NTekElWvn_GkdkawqBWc752ecC919cEqXYLIK461M).

**Comment by KasparsNaglis** [comment]
Desktop: https://www.figma.com/proto/QG9bQXrrt0MAh8QyfMr742/MUI-for-Figma-v5.4.0---Material-UI?page-id=8577%3A72000&node-id=8578%3A72001&viewport=746%2C380%2C0.54&scaling=min-zoom&starting-point-node-id=8578%3A72001

Mobile (It's a simple clickable prototype. For the best experience open the link with your smartphone): https://www.figma.com/proto/QG9bQXrrt0MAh8QyfMr742/MUI-for-Figma-v5.4.0---Material-UI?page-id=8580%3A71788&node-id=8580%3A72003&viewport=940%2C673%2C1.26&scaling=min-zoom

1. We should discuss what we can hide and what should be displayed.
2. Menu should be always white. It would make it easier to maintain and scale it. 
3. Wasn't able to satisfy the requirement about the tagline. Problem is that it's not even a tagline. It explains where the user has landed and this should be solved in the body section, not in the header.

**Comment by MillenniumFalconMechanic** [comment]
#### 2022-05-12 Meeting Notes
* Go forward with full version
* Show options for "more" subnav
* Flesh out search (e.g. active state on desktop, mobile)
* Refine mobile
* Interactive prototypes where helpful

**Comment by KasparsNaglis** [comment]
Updated screens: 

- Mobile: [https://www.figma.com/proto/QG9bQXrrt0MAh8QyfMr742/MUI-for-Figma-v5.4.0---Material-[…]2C484%2C1&scaling=min-zoom&starting-point-node-id=8580%3A72003](https://www.figma.com/proto/QG9bQXrrt0MAh8QyfMr742/MUI-for-Figma-v5.4.0---Material-UI?page-id=8580%3A71788&node-id=8580%3A72003&viewport=762%2C484%2C1&scaling=min-zoom&starting-point-node-id=8580%3A72003)
- Desktop: [https://www.figma.com/proto/QG9bQXrrt0MAh8QyfMr742/MUI-for-Figma-v5.4.0---Material-[…]ting-point-node-id=8578%3A72001&show-proto-sidebar=1&hide-ui=1](https://www.figma.com/proto/QG9bQXrrt0MAh8QyfMr742/MUI-for-Figma-v5.4.0---Material-UI?page-id=8577%3A72000&node-id=8627%3A72222&viewport=-6447%2C-52%2C1.84&scaling=min-zoom&starting-point-node-id=8578%3A72001&show-proto-sidebar=1&hide-ui=1)

**Comment by KasparsNaglis** [comment]
- Here is the final Figma file: https://www.figma.com/file/i4uZsYkKAML9ivi2TIo6ug/explore-dashboard?node-id=0%3A1
- Desktop Anvil Prototype: https://www.figma.com/proto/i4uZsYkKAML9ivi2TIo6ug/explore-dashboard?page-id=0%3A1&node-id=1%3A257&viewport=3486%2C368%2C0.66&scaling=min-zoom&starting-point-node-id=1%3A257&hide-ui=1
- Mobile Anvil prototype: https://www.figma.com/proto/i4uZsYkKAML9ivi2TIo6ug/explore-dashboard?page-id=1%3A1326&node-id=1%3A1490&viewport=3639%2C573%2C1&scaling=min-zoom&starting-point-node-id=1%3A1490
