### ISSUE TITLE
Add "Workspace" tab to AnVIL Catalog consortia detail page

### ISSUE THREAD

**Issue by NoopDog** [clevercanary/data-browser#704]
Add a "Workspace" tab to the AnVIL Catalog consortia detail page holding workspaces tagged with the consortia.

Similar to how the [workspaces](https://anvil-catalog.dev.singlecell.gi.ucsc.edu/explore/studies/phs000298/workspaces) tab is added to the anvil catalog page.
This may be all config.

**Comment by hunterckx** [comment]
Done
