### ISSUE TITLE
[HCA] Prepare demo of HCA Catalog

### ISSUE THREAD

**Issue by NoopDog** [clevercanary/data-browser#751]
#### Need
To demo the flexibility of the framework to HCA stakeholders and get folks thinking about a more integrated experience between the data browser and the wider community.

#### Approach 
Look at this catalog here:
https://www.ebi.ac.uk/humancellatlas/project-catalogue/

1. download the projects file https://api.ingest.archive.data.humancellatlas.org/projects/search/catalogue?page=0&size=1000
2. Use this to generate a TSV in the "files" section to power the site.
3. Extract off interesting attributes for the columns and detail pages to the tsv.
4. Configure a project entity and project detail page.
5. Create mappers etc to map from the tsv data structure to the fields needed to display.
6. Iterate till we have an interesting browser.

Would be great to get the institution, laboratory and contributors in there once we have some basics.

#### Entities
Make a single entity "Project".

Select some columns
- project name
- assay
- species

Select some filters
- same as columns 

Configure them.

#### Project Detail Page
Make project detail pages using the title, description and right channel key value pairs of assay, species.

**Comment by hunterckx** [comment]
Done
