### ISSUE TITLE
Fix lungmap dev deploy script

### ISSUE THREAD

**Issue by NoopDog** [clevercanary/data-browser#765]
upload: dist/explore/styles.d2394c30e7297535.css to s3://dev.explore.lungmap.net/explore/styles.d2394c30e7297535.css
upload: dist/explore/styles.d2394c30e7297535.css.map to s3://dev.explore.lungmap.net/explore/styles.d2394c30e7297535.css.map
upload: dist/explore/main.de40130249b6825c.js to s3://dev.explore.lungmap.net/explore/main.de40130249b6825c.js
upload: dist/explore/main.de40130249b6825c.js.map to s3://dev.explore.lungmap.net/explore/main.de40130249b6825c.js.map
$ aws s3 cp $BUCKET/explore/index.html $BUCKET/explore/index.html --metadata-directive REPLACE --cache-control max-age=0,no-cache,no-store,must-revalidate --content-type text/html    - aws cloudfront create-invalidation --distribution-id E21CJFOUWO9Q7X --paths "/*"
Unknown options: -,aws,cloudfront,create-invalidation,--distribution-id,E21CJFOUWO9Q7X,--paths,/*
Cleaning up project directory and file based variables

**Comment by MillenniumFalconMechanic** [comment]
Completed.
