### ISSUE TITLE
[HCA DB] View project species

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [clevercanary/data-browser#785]
#### Approach
* See [mocks](https://www.figma.com/file/i4uZsYkKAML9ivi2TIo6ug/HCA-Data-Explorer?node-id=237%3A1534&t=PLF6ISGGar3bRB7v-0).
* See `ProjectViewFactory` and `table-methods.rollupMetadata` for any existing special handling for species.
* Add test coverage - TBD.

**Comment by MillenniumFalconMechanic** [comment]
@frano-m , @NoopDog , let's discuss test coverage approaches.

**Comment by frano-m** [comment]
Tests TODO!
