### ISSUE TITLE
Update ESLint default settings

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [clevercanary/data-browser#79]
1. Validate current configuration is working as expected. For example, why does `npm run lint` not report an error or warning for `no-explicit-any`.
2. Add `sonarjs` as a plugin (e.g. `"plugin:sonarjs/recommended"`).
3. Add `sort-keys` to `rules`:

```
rules: {
  "sort-keys": [
      "error",
      "asc",
      {
        caseSensitive: true,
        minKeys: 2,
        natural: false,
      },
    ],
   ...
}

**Comment by NoopDog** [comment]
Complete
