### ISSUE TITLE
Add path aliases for images

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [clevercanary/data-browser#80]
Is it possible to create an alias for paths such as `import HcaLogo from "../../../images/hca-logo.png";` (in `header.stories.tsx`). See [Absolute Imports and Module path aliases](https://nextjs.org/docs/advanced-features/module-path-aliases) as a possible option?

**Comment by MillenniumFalconMechanic** [comment]
`npm run storybook`

**Comment by NoopDog** [comment]
Done!
