### ISSUE TITLE
[AnVIL DX] Track entity table sorted

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [clevercanary/data-browser#806]
**Currently blocked by #813 .**

#### Approach
* See #802  for implementation and modeling.
* Add trigger and tag in GTM.

#### Definition of Done
* Tag fired on sort of entity table column.

**Comment by AyyazAli** [comment]
@frano-m I've pushed the code to your [PR](https://github.com/clevercanary/data-explorer/pull/59). While tracking for Table Sort (#802) & pagination (#807 ) in `packages/data-explorer-ui/src/components/Table/table.tsx` it throws an error. While my other tracking for Entity Tab selected (#809) & (#808) working properly on `packages/data-explorer-ui/src/views/ExploreView/exploreView.tsx`.  Although I have created tracking in GTM to handle the tracking for the site. 

I'm not sure what's causing the issue, as the tracking codes are working properly fine for tab selection and Table filtration. 
I've attached the image file showing the exact error that it's throwing. It throws this error after I do `npx tsc` in `data-explorer-ui`. 

<img width="977" alt="image" src="https://user-images.githubusercontent.com/32508210/230516300-1ce5d48a-c543-434e-a16a-75b2961889c1.png">

**Comment by AyyazAli** [comment]
Can you also please confirm if line no 98, 162 & 182 will cause problem in `packages/data-explorer-ui/src/components/Table/table.tsx`.  I'm getting the entity tab value from exploreState and it might not be updated with the latest values.

**Comment by frano-m** [comment]
@AyyazAli, as discussed, to resolve the above error we need to change the imports to relative paths. ⭐

**Comment by MillenniumFalconMechanic** [comment]
Completed as per https://github.com/clevercanary/data-explorer/pull/63.
