### ISSUE TITLE
Update files to match new naming convention

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [clevercanary/data-browser#81]
#### Approach
* Component folders are capitalized. For example, `Citations`, `ComponentCreator`.
* Component and story files are camelcase. For example, `dataReleasePolicy.stories.tsx` and `dataRealeasePolicy.tsx`
* Core component and stories files are direct children of corresponding folder. For example, `/Links/links.tsx` and `/Links/links.stories.tsx`.
* Auxiliary component and stories files are nested under a `common` folder. For example, `/Links/components/Item/item.tsx`.
* See `Section` folder as a correct example.
* Utility folders such as `common`, `components` remain lowercase.
* Possibly use existing code mode?

#### Definition of Done
* Folder structure and folder and file naming match above for the `/explorer/app` directory.

**Comment by MillenniumFalconMechanic** [comment]
#### Approach
* Component folders are capitalized. For example, `Citations`, `ComponentCreator`.
* Component and story files are camelcase. For example, `dataReleasePolicy.stories.tsx` and `dataRealeasePolicy.tsx`
* Core component and stories files are direct children of corresponding folder. For example, `/Links/links.tsx` and `/Links/links.stories.tsx`.
* Auxiliary component and stories files are nested under a `common` folder. For example, `/Links/components/Item/item.tsx`.
* See `Section` folder as a correct example.
* Utility folders such as `common`, `components` remain lowercase.
* Possibly use existing code mode?

#### Definition of Done
* Folder structure and folder and file naming match above for the `/explorer` directory.

**Comment by NoopDog** [comment]
Not required
