### ISSUE TITLE
[AnVIL DX] User can access a query from a saved link

### ISSUE THREAD

**Issue by NoopDog** [clevercanary/data-browser#829]
1. On filter the filter goes into the address bar similar to https://data.humancellatlas.org/explore/projects?filter=%5B%7B%22facetName%22:%22biologicalSex%22,%22terms%22:%5B%22female%22%5D%7D%5D

2. When accessing a filter page, the filter state is loaded from the address bar. 

- [x] Technical design - where in the code will we put the side effect to modify the address bar and when will we sync address bar state with the app.
- [x] Implement!

**Comment by NoopDog** [comment]
complete

**Comment by MillenniumFalconMechanic** [comment]
See [dupe](https://github.com/clevercanary/data-browser/issues/677).
