### ISSUE TITLE
[HCA] Update hca-dcp config to point to prod azul

### ISSUE THREAD

**Issue by NoopDog** [clevercanary/data-browser#844]
The HCA dev instance seems to be empty (and has been for a day or two) to keep testing lets point the back end of our hca dev instance to produce URLs like:

https://service.azul.data.humancellatlas.org/index/projects?filters={}&size=25&catalog=dcp25

note the updated catalog and the prod endpoint.

**Comment by MillenniumFalconMechanic** [comment]
Completed.
