### ISSUE TITLE
Update ErrorBoundary fallback render to use Error component

### ISSUE THREAD

**Issue by frano-m** [clevercanary/data-browser#854]
Update the `_app.tsx` `ErrorBoundary` `fallbackRender` to use the `Error` component.

### Approach
- Use the `Error` component from `@clevercanary/data-explorer-ui` package.
- Configure props to pass to the component:
  - `errorMessage`,
  - `requestUrlMessage` and
  - `rootPath` (configured `redirectRootToPath` and possibly `NEXT_PUBLIC_BASE_PATH` if required?).
- Map any Axios errors as early as possible to a standard error type; no one outside of the service should need to know about Axios.

### Definition of Done
- Render Error component from `@clevercanary/data-explorer-ui` package when an error is thrown.
- Any Axios related errors are mapped as early as possible to a standard error type.

**Comment by MillenniumFalconMechanic** [comment]
Merged manually.
