### ISSUE TITLE
[DX] Retry Azul requests when it returns a 503 

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [clevercanary/data-browser#857]
#### Approach
* Retry 503's globally in Axios.
* See original [here](https://github.com/DataBiosphere/data-browser/issues/2559).

**Comment by BruceRodrigues** [comment]
- Limit the retries at 3
- Add a mock server to create a unit test for the retry logic

**Comment by MillenniumFalconMechanic** [comment]
Tracking in original repo.
