### ISSUE TITLE
Update AnVIL Explorer Header

### ISSUE THREAD

**Issue by NoopDog** [clevercanary/data-browser#877]
https://www.figma.com/proto/JOUDXkKfgivRNFdBsWDPEH/AnVIL-Data-Explorer?page-id=1008%3A14844&node-id=1008-16881&viewport=993%2C253%2C0.12&scaling=min-zoom&starting-point-node-id=1008%3A14845

**Comment by MillenniumFalconMechanic** [comment]
Superseded by https://github.com/DataBiosphere/data-browser/issues/3628.
