### ISSUE TITLE
[AnVIL CMG] On query export to terra show warning about missing files for datasets with access required.

### ISSUE THREAD

**Issue by NoopDog** [clevercanary/data-browser#900]
Not logged in - "Files for datasets with access "required" will be excluded from this export. To export all files matching your query, please sign in and, if necessary, request access."
Logged in - "Files for datasets with access "required" will be excluded from this export. To export all files matching your query, please request access."

**Comment by MillenniumFalconMechanic** [comment]
Superseded by https://github.com/DataBiosphere/data-browser/issues/3625.
